package com.allacsta.composesubmission.model

import com.allacsta.composesubmission.R


object CoffeeDataSource {
    val dummyCoffees = listOf(
        Coffee(1, R.drawable.americano, "Americano", 25000, "The americano finds its origins in World War II. Interestingly, American soldiers stationed in Italy didn’t care for the very strong espresso that was favoured in the country, therefore they tried to recreate their beloved drip coffee from back home by adding water to the espresso shot. The result? The americano that we know and love today."),
        Coffee(2, R.drawable.cappuccino, "Capucinno", 26500, "The cappuccino first came to Europe and America in 1980, around a similar time to the latte. Originating in Italy (as most good coffee does), lots of coffee from there has a name that when translated literally means how it’s made or what it includes – but the cappuccino is a little different. Apparently, the colouring of the espresso and frothed milk bore similarities to the hue of the Capuchin friar robes, and so, the wonderful beverage was dubbed the “cappuccino”."),
        Coffee(3, R.drawable.espresso, "Espresso", 20000, "As with many famous coffee recipes, the espresso was invented in Italy, around 100 years ago, and is credited to a man by the name of Luigi Bezzera, from Milan. He was the first to use a steam-pressure method of brewing coffee, which produced a strong cup of coffee faster than ever before. In fact, the name \"caffé espresso\" translates to \"pressed out coffee\", referring to the water being pushed through the finely ground coffee at a very high pressure. Espresso became increasingly popular when the demand for coffee increased in the late 1800s and early 1900s. By the 1940s, the process of making espresso had been properly fine-tuned, creating the espresso known and used cross the world."),
        Coffee(4, R.drawable.flat_white_hazelnut, "Flat White Hazelnut", 22000, "The flat white is the new kid on the block when it comes to coffee. Originating from Australia or New Zealand, depending on who you talk to, it is now filling menus in coffee shops around the world"),
        Coffee(5, R.drawable.hazelnut_latte, "Hazelnut Latte", 23000, "Press espresso coffee into a mug or heatproof glass. Froth hot milk using a milk frother or your espresso machine. Add hazelnut syrup to the espresso coffee and stir to combine. Pour the frothed milk into the cup"),
        Coffee(6, R.drawable.latte, "Latte", 18000, "The origins of the latte aren’t very clear as people have been combining coffee and milk for centuries. However, the silky beverage that we know and love today is thought to originate in America, hitting the peak of popularity in Seattle during the 80’s."),
        Coffee(7, R.drawable.latte_macchiato, "Latte Macchiato", 17000, "The origin of the name \"macchiato\" stems from baristas needing to show waiters the difference between an espresso shot and an espresso with a bit of milk in it. As the latter is \"marked\" or \"stained\" by the addition of milk, it was quickly given its name to highlight the addition. Unlike the cappuccino, originally being created exclusively for that morning coffee, the macchiato is the perfect afternoon coffee."),
        Coffee(8, R.drawable.picollo_late, "Picollo Late", 17000, "The term piccolo coffee is just short for piccolo latte coffee. So, A piccolo latte is a fresh roasted coffee that's comprised of a single shot of ristretto that's served in a demitasse glass and topped to the brim with latte-like steamed milk"),
        Coffee(9, R.drawable.vanilla_latte, "Vanilla Latte", 23000, "A vanilla latte is a very specific, and very iconic type of espresso-based drink. While you could just make some vanilla-flavored coffee, it's not the same thing. We make our vanilla latte using espresso coffee, steamed milk or alternative milk, and a house-made vanilla syrup"),
        Coffee(10, R.drawable.vietnam_drip, "Vietnam Drip", 23000, "The brewing type was first developed in 19th centuryFrance and quickly become the most popular way to prepare coffee. It involved putting ground coffee into a container between two chambers of a pot and adding heated water to the top chamber, the coffee was then percolated and dripped down through the coffee into the bottom serving receptacle. One of the biggest developments in drip coffee came in 1908 when a German woman called Amalie Auguste Melitta Bentz invented the first coffee filter. She soon patented her paper filter and established the Melitta company and eventually created the cone shaped filter you’re familiar with today. "),
        Coffee(11, R.drawable.cold_brew, "Cold Brew", 21000, "The earliest version of cold brew was called ‘Kyoto’ and it dates back to Japan in the 1600s. It was an incredibly popular drink in the city, so much so that they eventually made cold brew coffee machines, and made a spectacle out of brewing the beverage in public places. There has been some argument of whether cold brew was invented in Japan, as many believe that it was introduced to the country by Dutch traders that developed the process in order to transport large quantities of strong coffee that could later be reheated or enjoyed cold. "),
        Coffee(12, R.drawable.long_black, "Long Black", 20000, "Why is it called a long black?It's called a “Long Black” when the espresso comes after the water during the preparation process. It's called an “Americano” when the water comes after the espresso. Lungo stands for “Long” in Italian - it's a long espresso"),
    )
}